package grammar;

public enum NodeType {
	PROGRAM,TYPESPEC,VARDECL,ARRAYDECL,FUNDECL,PARMLIST,VARPARM,ARRAYPARM,
	COMPUND,STATEMENTLIST,STATEMENT,IFSTMT,WHILESTMT,RETURNSTMT,EXPRESSIONSTMT,EXPRESSION,
	ASSIGNEXPRESSION,SIMPLEEXPRESSION,CONST,VAR, CALL,ARRAYVAR,OVER,MULT, PLUS, MINUS, LT, LE, GT, GE, EQ, NE, ASSIGN, args, ID, VOIDTYPESPEC, INTTYPESPEC
}
